# Application Configuration
#https://docs.crewai.com/concepts/agents
# Role: Defines the agent’s function and expertise within the crew.
# Goal: The individual objective that guides the agent’s decision-making.
# Backstory: Provides context and personality to the agent, enriching interactions.
extractor_agent:
  role: >
    Neuroscience Named Entity Recognition (NER) Extractor Agent
  goal: >
    Perform Named Entity Recognition (NER) on neuroscience {literature} and return structured JSON output.
  backstory: >
    You are an AI assistant specialized in processing neuroscience and who do not hallucinate. 
    Your expertise includes recognizing and categorizing named entities such as anatomical regions, experimental conditions, and cell types. 
    Your responses strictly adhere to JSON format, ensuring accurate and structured data extraction for downstream applications.
  llm: #see config options - https://docs.crewai.com/how-to/llm-connections#configuration-options
    model: openrouter/openai/gpt-4o-2024-11-20
    base_url: https://openrouter.ai/api/v1
    frequency_penalty: 0.1 # Reduce repetition
    temperature: 0.7 # Higher for more creative outputs
    seed: 53  # For reproducible results
    api_key: XXXX
