flow:
  - id: extracted_structured_information
    agent_key: extractor_agent
    task_key: ner_extraction
    inputs:
      literature: "{{source_text}}"

  - id: align_structured_information
    agent_key: alignment_agent
    task_key: ner_alignment
    inputs:
      extracted_info: "{{output_of.extracted_structured_information}}"
    knowledge_source: extracted_info

  - id: judge_alignment
    agent_key: judge_agent
    task_key: ner_judgment
    inputs:
      aligned_structured_terms: "{{output_of.align_structured_information}}"
    knowledge_source: aligned_structured_terms
