# Application Configuration
#https://docs.crewai.com/concepts/tasks
extractor_agent_task:
  description: >
    From the given {literature} extract named entities from neuroscience statements. 
    A named entity is anything that can be referred to with a proper name. 
    Some common named entities in neuroscience articles are animal species (e.g., mouse, drosophila, zebrafish), anatomical regions (e.g., neocortex, mushroom body, cerebellum), experimental conditions (e.g., control, tetrodotoxin treatment, Scn1a knockout), and cell types (e.g., pyramidal neuron, direction-sensitive mechanoreceptor, oligodendrocyte)
  expected_output: >
    Provide the output in the following format.
    "extracted_ner_terms": {
        "1": [
          {
            "entity": "mouse",
            "label": "ANIMAL_SPECIES",
            "sentence": "These particles were visualized by fluorescent immunohistochemistry using mouse monoclonal anti-human myelin basic protein (MBPh) antibody (clone SMI-99).",
            "start": 79,
            "end": 84,
            "paper_location": "methods",
            "paper_title": "Concentration of myelin debris-like myelin basic protein-immunoreactive particles in the distal (anterior)-most part of the myelinated region in the normal rat optic nerve",
            "doi": "10.1101/2025.03.19.643597"
          }
        ],
        "2": [
          {
            "entity": "oligodendrocyte",
            "label": "CELL_TYPE",
            "sentence": "Individual oligodendrocytes provide, on average, 16 near axons with single myelin segments about 200 µm in length (Butt and Ransom, 1993).",
            "start": 14,
            "end": 29,
            "paper_location": "discussion",
            "paper_title": "Concentration of myelin debris-like myelin basic protein-immunoreactive particles in the distal (anterior)-most part of the myelinated region in the normal rat optic nerve",
            "doi": "10.1101/2025.03.19.643597"
          }
        ],
        "3": [
          {
            "entity": "cerebellum",
            "label": "ANATOMICAL_REGION",
            "sentence": "Myelin basic protein, human (MBPh) The mouse monoclonal antibody against the human myelin basic protein (clone SMI-99; Covance, Princeton, NJ) detects 4 bands between 14 and 21 kDa, corresponding to 4 myelin basic protein (MBP) isoforms on immunoblots of the mouse cerebellum (Dyer et al.).",
            "start": 293,
            "end": 303,
            "paper_location": "methods",
            "paper_title": "Concentration of myelin debris-like myelin basic protein-immunoreactive particles in the distal (anterior)-most part of the myelinated region in the normal rat optic nerve",
            "doi": "10.1101/2025.03.19.643597"
          }
        ],
    }
    

  agent: extractor_agent
